---
repos:
    - repo: "https://gitlab.com/pycqa/flake8"
      rev: 3.7.8  # 3.6.0 doesn't contain this configuration file.
      hooks:
          - id: flake8
            additional_dependencies: ["flake8-colors"]
    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.16.0
      hooks:
          - id: yamllint
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.720
      hooks:
          - id: mypy
            args: ["--ignore-missing-imports"]
            # Ensures that pachyderm is available, which will avoid a number of typing issues
            additional_dependencies: ["pachyderm"]
    - repo: https://github.com/pre-commit/pygrep-hooks
      rev: v1.4.1
      hooks:
          - id: python-check-mock-methods
          - id: rst-backticks
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
          - id: trailing-whitespace
          - id: check-executables-have-shebangs
