# Needed for python 3.7
dist: xenial
language: python
python:
    - 3.6
    - 3.7
sudo: required
# Use cache with pip to save time.
cache: pip
install:
    # Needed on a separate line so that the packages install properly.
    - pip install --upgrade numpy cython
    - pip install --upgrade -e .[tests,dev,docs]
script:
    # Since we ran the tests above, we don't need to run them here.
    # Check code quality
    - flake8 .
    # Run the tests
    - pytest -l -vv --cov=reaction_plane_fit --cov-branch -m "not root" --durations=5 tests/
    # Check that the docs build successfully
    - pushd docs && make html && popd
after_success:
    # Upload coverage report to codecov.
    - bash <(curl -s https://codecov.io/bash)
jobs:
    include:
        - stage: deploy
          python: 3.7
          deploy:
              provider: pypi
              user: rehlers
              password:
                  secure: r/IfkfL2wml/roFUVbNbhbzv9kUWu9mDWNfHYLFAmNIMLv4bMzagui+UBUb0QICVUccm5RVjEjESO3g0cPg37meci20Dq9dYgCsJHkjeF1n/BlfnHCfFbg+nhuFq8vqwfWxhEqpvV9oArrWGipwi70p8F7+WJS4bxAhmf6YhCy52LsrPswX3DNdlE9X5esAC5upWUIZfLDTd9tz3q8M6DuZEVwS1d3RZlZYuNncbAOmEhbTnJDdhCYy2o1LAmJ1brceHmq/ZStKPjdqb8bapS+QJte/3E1IuMudQb38AWOpBPJpE/MnjWEXln9e2vjFgEkr49SBnW+fbUL/vkwa+JHF0UbfPUzRrr/4i4a1jN62I069LSvzOxt8dE66uU2O8XEF3PHj/kjTv14tDWxwqG8Q/dV2FnnpPLAqJB8yKbSYU8WINdmNqO6kq4hNHpLHTNFP1zxwSov4bJsJsSSLe8nvuJI0eJmrTPQAVz5XZpb0N/byucgE9mnA/JSHnHoEA//VwE3TKmRGF/xZ5dBnVYZObuQvAeercvsxS9JYt268Z0cFaFOqWFg+uSNjMcHP2BIeatOJDVsS9q1pXZv5/0f6FFBGxNjQoLmoXVuMl87pER6ubllUqn13itX3gXtJ7H1baGlyZ496zjY2qyXj+Xlsj4GppLEcLQL2nlZ0w45I=
              distributions: sdist bdist_wheel
              on:
                  tags: true
