# Needed for python 3.7
dist: xenial
language: python
python:
    - 3.6
    - 3.7
sudo: required
# Use cache with pip to save time.
cache: pip
install:
    # Needed on a separate line so that the packages install properly.
    - pip install --upgrade numpy cython
    - pip install --upgrade -e .[tests,dev,docs]
script:
    # Since we ran the tests above, we don't need to run them here.
    # Check code quality
    - flake8 .
    # Run the tests
    - pytest -l -vv --cov=reaction_plane_fit --cov-branch -m "not root" --durations=5 tests/
    # Check that the docs build successfully
    - pushd docs && make html && popd
after_success:
    # Upload coverage report to codecov.
    - bash <(curl -s https://codecov.io/bash)
jobs:
    include:
        - stage: deploy
          python: 3.7
          deploy:
              provider: pypi
              user: rehlers
              password:
                  secure: bhZmO8hypNKPMjt2x16lOT17nOo8/5o3Il2ZA86bZcD3L4ojkeYXXzYX+iLaVIUe1Y1JtyQVTxClc6PO1k+7INTD8BLalAiGAHZatZe9u4puQeZ+un44/3oE2J/RjAgGcVqp8ZqtoRgr01SP0Bt5gIHqoow31323fjFlHYXiuuy4lMnNAKeTHUqvdWzZAO5KxO+FwcWqwgWOIyiZUlzOOnmkGFJJrAxjSH2AijDn9i+p8hWVvcLrryGfaNhsCCd5CV4/7SVnc1EQfjYS8CSaFuhp17HW2BWX7m3upkPzk/f7UW7ZAUuAsGhaoTKU53kPhQ5OK1Ta3PEa5vPtF7fZlLq8QTD7cFbWUdwjoNJC+vUv3vXWx1BoBW0hlxRwEQX9wvm1179H67OHSzJbFTBAKxrScKNW2Kd3aDfPI1ARBNOKRjT4ZKX7VEmOPLr2GZvSeO8DIJfnANAYIPtnKD76H1zylVB5xNH197D/ks2iJz+m08Vib5mXngNxG64VUIKxn7pSiBFqgoLN+JrY1xSMxdmMlS0geNmIGBoGr4uQ3awTbsDhGx9B3dYZSwGM5eKtqsd6tNw+cZVTla0yQR3wAzaXeaNzxLSeZq2aQ9L5kPHr2OxJ5+pr4Hf700gSwyJHYASD3L13a0RzoBSGWhTGgeoL/rz9FE88i95BN6e/Be8=
              distributions: sdist bdist_wheel
              on:
                  tags: true
